[build]
  publish = "."
  command = "true"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "no-cache"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
